### ISSUE TITLE
pve_disk_usage_bytes = 0.0

### ISSUE THREAD

**Issue by robonuka** [prometheus-pve/prometheus-pve-exporter#118] opened 2022-08-23 06:59 UTC
Hi!
Your pve-exporter is great! But it has only one bad thing:
There is "pve_disk_usage_bytes = 0.0" for any VM :((
Please fix that.

**Comment by znerol** [comment] 2022-08-23 11:19
Duplicate of #77

**Closed by znerol** 2022-08-23 11:19 UTC
