### ISSUE TITLE
Information retrieval from multiple vm disks

### ISSUE THREAD

**Issue by Tristan-GG** [prometheus-pve/prometheus-pve-exporter#295] opened 2024-10-30 10:41 UTC
Hello !

I'm reporting this little lack of information, which I think you probably already know about, but I'd like to point it out anyway, just in case.

You don't get information about all the vm disks but only about the first disk, for example here is my conf on proxmox :

<img width="307" alt="msedge_YseJRYibbf" src="https://github.com/user-attachments/assets/bdd7872d-aaf2-4d36-83b7-7b15d1a7c90b">

And here is the information provided by the vm exporter :

pve_disk_size_bytes{id="qemu/102"} 2.147483648e+010

That's it for the information, it may also be a mistake on my part, if so sorry for the inconvenience.

Thanks in advance!

**Comment by znerol** [comment] 2024-10-30 10:56
This is a limitation of the Proxmox API. We are getting our metrics from [cluster/resources](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/resources). That endpoint only reports usage for the startup disk.

Duplicate of #12.

**Closed by znerol** 2024-10-30 10:56 UTC
