### ISSUE TITLE
Set urllib3.disable_warnings() when verify_ssl: false

### ISSUE THREAD

**Issue by peterablehmann** [prometheus-pve/prometheus-pve-exporter#228] opened 2024-02-10 00:07 UTC
I've set the verify_ssl option to false because I connect via localhost and don't have a valid ssl cert for localhost.

This leads to an unecessary amount of log messages when the exporter queries:
```
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]: /opt/prometheus-pve-exporter/lib/python3.11/site-packages/urllib3/connectionpool.py:1100: InsecureRequestWarning: Unverified HTTPS request is being made to host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
Feb 07 00:49:47 proxmox-xnee-de pve_exporter[3804304]:   warnings.warn(
```

This makes Syslog impossible to read.

When verify_ssl is set to false the pve exporter should set urllib3.disable_warnings() to keep syslog clean from unnecessary warnings.

**Comment by znerol** [comment] 2024-02-10 10:21
Duplicate of #129

**Comment by znerol** [comment] 2024-02-10 10:22
> When verify_ssl is set to false the pve exporter should set urllib3.disable_warnings() to keep syslog clean from unnecessary warnings.

No. These warnings are there for a reason.

**Closed by znerol** 2024-02-10 10:21 UTC
