### ISSUE TITLE
Feature Request - All disk information

### ISSUE THREAD

**Issue by heapdavid** [prometheus-pve/prometheus-pve-exporter#299] opened 2024-11-26 13:23 UTC
Hi,

Currently the exporter gives us the size etc of the boot disk, but if a VM has more than one disk it doesn't appear anywhere in the metrics (as far as I can tell).

It would be good to be able to see each disk, the vm it's related to, if it's attached or not, which storage it's on etc.

**Comment by znerol** [comment] 2024-11-26 14:32
This is a limitation of the Proxmox API. We are getting our metrics from [cluster/resources](https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/resources). That endpoint only reports usage for the startup disk.

Duplicate of #12.

**Closed by znerol** 2024-11-26 14:32 UTC
